name:                proid
version:             0.5.2.0
license:             GPL-3
author:              "Christopher"

extra-source-files:
- README.org

dependencies:
- base >= 4.7 && < 5
- process
- directory
- temporary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  proid:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
