name: proid
version: 0.6.0.0
license: GPL-3
author: "Christopher"

extra-source-files:
  - README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitLab at https://gitlab.com/rehposuite/proid

dependencies:
  - base >= 4.7 && < 5
  - process
  - directory
  - temporary
  - ansi-terminal
  - string-qq
  - filepath

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  proid:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
